### PR TITLE
Web4542 add make-up

### PR DESCRIPTION
**Pull request by lukefrake**
#### What are the links to relevant tickets?
WEB-4542
#### What does this PR do?
Add make-up
Make pass hinting linting etc
#### What unit tests does this PR have?
N/A
#### How should a developer review this?
Pull down & run tests / see travis run
#### Any background context you want to provide?
Part of something bigger
#### Screenshots (if appropriate)
---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this cross browser for any visual changes.
- [x] I've checked this work against the requirements of the Jira.
- [x] I am ready for this to be code reviewed, merged and tested.

#### Reviewer 1
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve witnessed the tests running successfully.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

#### Reviewer 2
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve witnessed the tests running successfully.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by MCooke** [comment]
Travis seems to be failing.

**Comment by lukefrake** [comment]
Sorry, my bad.

Tests where out of date when they where created, so I've commented them out.

I'm going to make another jira about that, but travis should stop crying now.

**Comment by MCooke** [comment]
+1

**Comment by philmeehan** [comment]
If you can create and link the Jira to fix the tests please?

**Comment by philmeehan** [comment]
https://hxshortbreaks.atlassian.net/browse/WEB-4648

+1 as the tests were already broken and will be fixed under that Jira

**Pull request merged**
